# -*- coding: utf-8 -*-
"""ml project_credit_risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlj0xuhq7yMK9KIpX5bMzgXKyhfkDppm

# data collection
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('/content/credit_risk_dataset.csv')
data.head()

"""# data preprocessing"""

data.info()

data.shape

data.isnull().sum()

"""# nulls imputation"""

data_MORTGAGE = data[(data['person_income'] >=10000) & (data['person_income'] <=15000)
& (data['person_home_ownership'] == 'MORTGAGE')]['person_emp_length'].median()
data_MORTGAGE

data.loc[(data['person_emp_length'].isna()) & (data['person_home_ownership'] == 'MORTGAGE'), 'person_emp_length'] = data_MORTGAGE

# checking the nulls imputed or not
data[(data['person_income'] >=10000) & (data['person_income'] <=15000)
& (data['person_home_ownership'] == 'MORTGAGE')]

data.isnull().sum()

data_rent = data[(data['person_income'] >=10000) & (data['person_income'] <=15000)
& (data['person_home_ownership'] == 'RENT')]['person_emp_length'].median()
data_rent

data.loc[(data['person_emp_length'].isna()) & (data['person_home_ownership'] == 'RENT'), 'person_emp_length'] = data_rent

# checking the nulls imputed or not
data[(data['person_income'] >=10000) & (data['person_income'] <=15000)
& (data['person_home_ownership'] == 'RENT')]

data.isnull().sum()

data_OWN = data[(data['person_income'] >=10000) & (data['person_income'] <=15000)
& (data['person_home_ownership'] == 'OWN')]['person_emp_length'].median()
data_OWN

data.loc[(data['person_emp_length'].isna()) & (data['person_home_ownership'] == 'OWN'), 'person_emp_length'] = data_OWN

# checking the nulls imputed or not
data[(data['person_income'] >=10000) & (data['person_income'] <=15000)
& (data['person_home_ownership'] == 'OWN')]

data.isnull().sum()

data.head()

data.isnull().sum()

loan_int_rate1 = np.round(data[(data['loan_percent_income'] >=0.25) & (data['loan_percent_income'] <=0.70)
& (data['loan_amnt'] >= 1000) & (data['loan_status'] <= 7000) & (data['loan_status'] == 1)]['loan_int_rate'].mean(),2)
print(loan_int_rate1)
loan_int_rate2 = np.round(data[(data['loan_percent_income'] >=0.25) & (data['loan_percent_income'] <=0.70)
& (data['loan_amnt'] >= 7100) & (data['loan_status'] <= 15000) & (data['loan_status'] == 1)]['loan_int_rate'].mean(),2)
print(loan_int_rate2)
loan_int_rate3 = np.round(data[(data['loan_percent_income'] >=0.25) & (data['loan_percent_income'] <=0.70)
& (data['loan_amnt'] >= 15100) & (data['loan_status'] <= 21000) & (data['loan_status'] == 1)]['loan_int_rate'].mean(),2)
print(loan_int_rate3)
loan_int_rate4 = np.round(data[(data['loan_percent_income'] >=0.25) & (data['loan_percent_income'] <=0.70)
& (data['loan_amnt'] >= 21100) & (data['loan_status'] <= 27000) & (data['loan_status'] == 1)]['loan_int_rate'].mean(),2)
print(loan_int_rate4)
loan_int_rate5 = np.round(data[(data['loan_percent_income'] >=0.25) & (data['loan_percent_income'] <=0.70)
& (data['loan_amnt'] >= 27100) & (data['loan_status'] <= 35000) & (data['loan_status'] == 1)]['loan_int_rate'].mean(),2)
print(loan_int_rate5)

data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 1), 'loan_int_rate'] = loan_int_rate1
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 1), 'loan_int_rate'] = loan_int_rate2
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 1), 'loan_int_rate'] = loan_int_rate3
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 1), 'loan_int_rate'] = loan_int_rate4
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 1), 'loan_int_rate'] = loan_int_rate5

data.isnull().sum()

loan_int_rate11 = np.round(data[(data['loan_percent_income'] >=0.1) & (data['loan_percent_income'] <=0.25)
& (data['loan_amnt'] >= 1000) & (data['loan_status'] <= 7000) & (data['loan_status'] == 0)]['loan_int_rate'].mean(),2)
print(loan_int_rate11)
loan_int_rate22 = np.round(data[(data['loan_percent_income'] >=0.1) & (data['loan_percent_income'] <=0.25)
& (data['loan_amnt'] >= 7100) & (data['loan_status'] <= 15000) & (data['loan_status'] == 0)]['loan_int_rate'].mean(),2)
print(loan_int_rate22)
loan_int_rate33 = np.round(data[(data['loan_percent_income'] >=0.1) & (data['loan_percent_income'] <=0.25)
& (data['loan_amnt'] >= 15100) & (data['loan_status'] <= 21000) & (data['loan_status'] == 0)]['loan_int_rate'].mean(),2)
print(loan_int_rate33)
loan_int_rate44 = np.round(data[(data['loan_percent_income'] >=0.1) & (data['loan_percent_income'] <=0.25)
& (data['loan_amnt'] >= 21100) & (data['loan_status'] <= 27000) & (data['loan_status'] == 0)]['loan_int_rate'].mean(),2)
print(loan_int_rate44)
loan_int_rate55 = np.round(data[(data['loan_percent_income'] >=0.1) & (data['loan_percent_income'] <=0.25)
& (data['loan_amnt'] >= 27100) & (data['loan_status'] <= 35000) & (data['loan_status'] == 0)]['loan_int_rate'].mean(),2)
print(loan_int_rate55)

data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 0), 'loan_int_rate'] = loan_int_rate11
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 0), 'loan_int_rate'] = loan_int_rate22
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 0), 'loan_int_rate'] = loan_int_rate33
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 0), 'loan_int_rate'] = loan_int_rate44
data.loc[(data['loan_int_rate'].isna()) & (data['loan_status'] == 0), 'loan_int_rate'] = loan_int_rate55

data.isnull().sum()

data.shape

data.describe()

num_cols = ['person_age', 'person_income', 'person_emp_length',
            'loan_amnt', 'loan_int_rate', 'loan_percent_income',
            'cb_person_cred_hist_length']

plt.figure(figsize=(18, 8))  # Set a big figure for clarity

for i, col in enumerate(num_cols, 1):
    plt.subplot(3, 3, i)  # 3 rows, 3 columns, position i
    sns.histplot(data[col], bins=30, kde=True)
    plt.title(f'Histogram of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
plt.tight_layout()
plt.show()

# for outliers
plt.figure(figsize=(15, 8))
for i, col in enumerate(num_cols, 1):
    plt.subplot(2, 4, i)
    sns.boxplot(y=data[col])
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

# for categorical
cat_cols = ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']
plt.figure(figsize=(12, 8))
for i, col in enumerate(cat_cols, 1):
    plt.subplot(2, 2, i)
    sns.countplot(data=data, x=col, hue='loan_status')
    plt.title(f'{col} distribution by Loan Status')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.legend(title='Loan Status')
    plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

# Correlation
plt.figure(figsize=(10,8))
sns.heatmap(data[num_cols + ['loan_status']].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# checking the any relation between person_age vs cb_person_cred_hist_length
plt.figure(figsize=(8, 6))
sns.scatterplot(data=data, x='person_age', y='cb_person_cred_hist_length')
plt.title('person_age vs cb_person_cred_hist_length')
plt.xlabel('Person Age')
plt.ylabel('Credit History Length')
plt.show()

data['loan_intent'].unique() # onehot

from sklearn.preprocessing import OneHotEncoder

onc_hot = OneHotEncoder(sparse_output=False)
transform_loan_intent = pd.DataFrame(onc_hot.fit_transform(data[['loan_intent']]),
                                 columns = onc_hot.get_feature_names_out(['loan_intent']), index=data.index)
data[transform_loan_intent.columns] = transform_loan_intent

data['person_home_ownership'].unique()

onc_hot = OneHotEncoder(sparse_output=False)
transform_person_home_ownership = pd.DataFrame(onc_hot.fit_transform(data[['person_home_ownership']]),
                                 columns = onc_hot.get_feature_names_out(['person_home_ownership']))
data[transform_person_home_ownership.columns] = transform_person_home_ownership

data.drop(['person_home_ownership','loan_intent'],axis =1, inplace = True)

data['loan_grade'].unique() # ordinal

from sklearn.preprocessing import OrdinalEncoder
odr_enc = OrdinalEncoder(categories=[['A','B','C','D','E','F','G']])
transform_loan_grade = pd.DataFrame(odr_enc.fit_transform(data[['loan_grade']]),
                                 columns = odr_enc.get_feature_names_out(['loan_grade']))
data[transform_loan_grade.columns] = transform_loan_grade

data['cb_person_default_on_file'].unique()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['cb_person_default_on_file'] = le.fit_transform(data['cb_person_default_on_file'])

"""# segerate input's and output's"""

# segregate inputs and output
x = data.drop(columns=['loan_status'])
y = data['loan_status']

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
x_train = pd.DataFrame(x_train_scaled, columns=x_train.columns, index=x_train.index)
x_test = pd.DataFrame(x_test_scaled, columns=x_test.columns, index=x_test.index)

"""# model building"""

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, roc_curve,auc
from sklearn.model_selection import RandomizedSearchCV

"""## logistic model buliding

"""

logistc = LogisticRegression()
logistc.fit(x_train, y_train)

y_test_pred = logistc.predict(x_test)
y_test_pred

print("Training Score:", logistc.score(x_train, y_train))
print("Testing Score:", logistc.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning LogisticRegression model"""

pram_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'penalty': ['l1', 'l2'],
    'max_iter': [100, 200, 300, 400, 500]
}

grid = RandomizedSearchCV(LogisticRegression(),cv = 5, param_distributions = pram_grid)
grid.fit(x_train, y_train)

print(grid.best_params_)

logistic_tuning = grid.best_estimator_

print("Training Score:", logistic_tuning.score(x_train, y_train))
print("Testing Score:", logistic_tuning.score(x_test, y_test))

"""## KNN model buliding"""

KNN = KNeighborsClassifier()
KNN.fit(x_train, y_train)

y_test_pred = KNN.predict(x_test)
y_test_pred

print("Training Score:", KNN.score(x_train, y_train))
print("Testing Score:", KNN.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning for KNN model"""

pram_grid = {
    'n_neighbors': range(1, 21),
    'weights': ['uniform', 'distance']
}

grid = RandomizedSearchCV(KNeighborsClassifier(),cv = 5, param_distributions = pram_grid)
grid.fit(x_train, y_train)

print(grid.best_params_)

KNN_tuning = grid.best_estimator_

print("Training Score:", KNN_tuning.score(x_train, y_train))
print("Testing Score:", KNN_tuning.score(x_test, y_test))

"""## decision tree model"""

DT = DecisionTreeClassifier()
DT.fit(x_train, y_train)

y_test_pred = DT.predict(x_test)
y_test_pred

print("Training Score:", DT.score(x_train, y_train))
print("Testing Score:", DT.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning the DT model"""

grid_pram = {
    'criterion': ['gini', 'entropy'],
    'max_depth': range(1,10,1),
    'min_samples_split': range(2,10,1),
    'min_samples_leaf': range(1,10,1),
}

grid = RandomizedSearchCV(DecisionTreeClassifier(),cv = 5,param_distributions = grid_pram)
grid.fit(x_train, y_train)

print(grid.best_params_)

DT_tuning = grid.best_estimator_

print("Training Score:", DT_tuning.score(x_train, y_train))
print("Testing Score:", DT_tuning.score(x_test, y_test))

"""## RandomForest model"""

RF = RandomForestClassifier()
RF.fit(x_train, y_train)

y_test_pred = RF.predict(x_test)
y_test_pred

print("Training Score:", RF.score(x_train, y_train))
print("Testing Score:", RF.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning the RandomForest model"""

grid_pram = {
    'n_estimators': range(10,100,10),
    'max_depth': range(1,10,1),
    'min_samples_split': range(2,10,1),
    'min_samples_leaf': range(1,10,1),
}

grid = RandomizedSearchCV(RandomForestClassifier(),cv = 5,param_distributions = grid_pram)
grid.fit(x_train, y_train)

print(grid.best_params_)

rf_tuning  = grid.best_estimator_

print("Training Score:", rf_tuning.score(x_train, y_train))
print("Testing Score:", rf_tuning.score(x_test, y_test))

"""## SVM"""

SVM = SVC()
SVM.fit(x_train, y_train)

y_test_pred = SVM.predict(x_test)
y_test_pred

print("Training Score:", SVM.score(x_train, y_train))
print("Testing Score:", SVM.score(x_test, y_test))

print("Accuracy:", accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

"""## after tuning the SVC model"""

pram_grid = {
    'C': [0.1, 1, 10, 12],
    'gamma': [1, 0.1, 0.01, 0.001],
}

grid = RandomizedSearchCV(SVC(),cv = 5,param_distributions = pram_grid)
grid.fit(x_train, y_train)

print(grid.best_params_)

svc_tuning = SVC(C=10, gamma=0.1)
svc_tuning.fit(x_train, y_train)

print("Training Score:", svc_tuning.score(x_train, y_train))
print("Testing Score:", svc_tuning.score(x_test, y_test))